-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS "dimplayers"
(
    idplayer character varying(10),
    nameplayer character varying(100),
    PRIMARY KEY (idplayer)
);

CREATE TABLE IF NOT EXISTS "factboxscores"
(   
    idgameteamplayer character varying(50),
    idgameteam character varying(15),
    idplayer character varying(10),
    idteam character varying(10),
    iddate date,
    min integer,
    fgm integer,
    fga integer,
    p_fg numeric(4,3),
    fg2m integer,
    fg2a integer,
    p_fg2 numeric(4,3),
    fg3m integer,
    fg3a integer,
    p_fg3 numeric(4,3),
    ftm integer,
    fta integer,
    p_ft numeric(4,3),
    oreb integer,
    dreb integer,
    treb integer,
    ast integer,
    stl integer,
    blk integer,
    tov integer,
    pf integer,
    pts integer,
    plusminus integer,
    PRIMARY KEY (idgameteamplayer)
);

CREATE TABLE IF NOT EXISTS "dimdate"
(
    iddate date,
    PRIMARY KEY (iddate)
);

CREATE TABLE IF NOT EXISTS "dimmatches"
(
    idgameteam character varying(15),
    slugseason character(7),
    typeseason character varying(30),
    slugmatchup character varying(15),
    slugteam character(3),
    slugopponent character(3),
    PRIMARY KEY (idgameteam)
);

CREATE TABLE IF NOT EXISTS "dimteams"
(
    idteam character varying(10),
    nameteam character varying(50),
    PRIMARY KEY (idteam)
);

ALTER TABLE IF EXISTS "factboxscores"
    ADD FOREIGN KEY (idgameteam)
    REFERENCES "dimmatches" (idgameteam) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "factboxscores"
    ADD FOREIGN KEY (idplayer)
    REFERENCES "dimplayers" (idplayer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "factboxscores"
    ADD FOREIGN KEY (idteam)
    REFERENCES "dimteams" (idteam) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "factboxscores"
    ADD FOREIGN KEY (iddate)
    REFERENCES "dimdate" (iddate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;